### ISSUE TITLE
error: file not found: src/Tests/bin/Release/CoiniumServ.Tests.dll

### ISSUE THREAD

**Issue by L5hunter** [bonesoul/CoiniumServ#722]
Hello! I was running the build.sh file for the first time, and this happened...

Project "/home/harm/CoiniumServ/build/CoiniumServ.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Release|Mixed Platforms".
        Target Build:
                Project "/home/harm/CoiniumServ/deps/csredis/CSRedis/CSRedis.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Release Platform: AnyCPU
                                Created directory "bin/Release/"
                                Created directory "obj/Release/"
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool /usr/bin/dmcs execution started with arguments: /noconfig /debug:full /optimize+ /out:obj/Release/csredis.dll Events.cs Internal/Commands/RedisArray.cs Internal/Commands/RedisRoleCommand.cs Exceptions.cs Internal/Commands/RedisIsMasterDownByAddrCommand.cs Internal/Commands/RedisSlowLogCommand.cs Internal/IRedisConnector.cs Internal/MockConnector.cs Internal/DefaultConnector.cs Internal/RedisListener.cs Internal/MonitorListener.cs Internal/RedisPipeline.cs Internal/SubscriptionListener.cs Internal/RedisTransaction.cs Internal/Utilities/RedisArgs.cs Internal/Commands/RedisBool.cs Internal/Commands/RedisBytes.cs Internal/Commands/RedisDate.cs Internal/Commands/RedisFloat.cs Internal/Commands/RedisHash.cs Internal/Commands/RedisInt.cs Internal/Commands/RedisScanCommand.cs Internal/Commands/RedisTuple.cs Internal/Commands/RedisObject.cs Internal/Commands/RedisStatus.cs Internal/Commands/RedisString.cs Internal/Commands/RedisSubscription.cs Internal/RedisConnection.cs Internal/IO/RedisReader.cs Properties/AssemblyInfo.cs RedisClient.cs Internal/RedisCommand.cs RedisClient.Async.cs RedisClient.Sync.cs RedisSentinelClient.cs RedisSentinelClient.Async.cs RedisSentinelManager.cs Internal/IO/RedisWriter.cs Internal/Utilities/Serializer.cs Types.cs RedisSentinelClient.Sync.cs /target:library /define:TRACE /doc:bin/Release/csredis.XML /platform:AnyCPU /reference:/usr/lib/mono/4.0/System.dll /reference:/usr/lib/mono/4.0/System.Xml.Linq.dll /reference:/usr/lib/mono/4.0/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.0/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.0/System.Data.dll /reference:/usr/lib/mono/4.0/System.Xml.dll /reference:/usr/lib/mono/4.0/System.Core.dll /warn:4
Internal/Commands/RedisSubscription.cs(15,18): warning CS0219: The variable `count' is assigned but its value is never used
Internal/IO/RedisReader.cs(56,17): warning CS0219: The variable`bytes_remaining' is assigned but its value is never used
                        Target DeployOutputFiles:
                                Copying file from '/home/harm/CoiniumServ/deps/csredis/CSRedis/obj/Release/csredis.dll.mdb' to '/home/harm/CoiniumServ/deps/csredis/CSRedis/bin/Release/csredis.dll.mdb'
                                Copying file from '/home/harm/CoiniumServ/deps/csredis/CSRedis/obj/Release/csredis.dll' to '/home/harm/CoiniumServ/deps/csredis/CSRedis/bin/Release/csredis.dll'
                Done building project "/home/harm/CoiniumServ/deps/csredis/CSRedis/CSRedis.csproj".
                Project "/home/harm/CoiniumServ/src/libCoiniumServ/libCoiniumServ.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Release Platform: AnyCPU
                                Created directory "bin/Release/"
                                Created directory "obj/Release/"
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool /usr/bin/dmcs execution started with arguments: /noconfig /debug:full /optimize+ /out:obj/Release/libCoiniumServ.dll Properties/AssemblyInfo.cs Versions/VersionInfo.cs /target:library /define:TRACE /reference:/usr/lib/mono/4.0/System.dll /reference:/usr/lib/mono/4.0/System.Xml.Linq.dll /reference:/usr/lib/mono/4.0/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.0/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.0/System.Data.dll /reference:/usr/lib/mono/4.0/System.Xml.dll /reference:/usr/lib/mono/4.0/System.Core.dll /warn:4
                        Target DeployOutputFiles:
                                Copying file from '/home/harm/CoiniumServ/src/libCoiniumServ/obj/Release/libCoiniumServ.dll.mdb' to '/home/harm/CoiniumServ/src/libCoiniumServ/bin/Release/libCoiniumServ.dll.mdb'
                                Copying file from '/home/harm/CoiniumServ/src/libCoiniumServ/obj/Release/libCoiniumServ.dll' to '/home/harm/CoiniumServ/src/libCoiniumServ/bin/Release/libCoiniumServ.dll'
                Done building project "/home/harm/CoiniumServ/src/libCoiniumServ/libCoiniumServ.csproj".
                Project "/home/harm/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj" (default target(s)):
                        Target RestorePackages:
                                Executing: mono --runtime=v4.0.30319 /home/harm/CoiniumServ/build/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/home/harm/CoiniumServ/build/"
                                Could not load type 'NuGet.MSBuildProjectUtility' from assembly 'NuGet, Version=2.8.50506.491, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
/home/harm/CoiniumServ/build/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 /home/harm/CoiniumServ/build/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/home/harm/CoiniumServ/build/"' exited with code: 1.
                        Task "Exec" execution -- FAILED
                        Done building target "RestorePackages" in project "/home/harm/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj".-- FAILED
                Done building project "/home/harm/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/home/harm/CoiniumServ/build/CoiniumServ.sln".-- FAILED
Done building project "/home/harm/CoiniumServ/build/CoiniumServ.sln".-- FAILED

Build FAILED.

Warnings:

/home/harm/CoiniumServ/build/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/harm/CoiniumServ/deps/csredis/CSRedis/CSRedis.csproj (default targets) ->
/usr/lib/mono/4.0/Microsoft.CSharp.targets (CoreCompile target) ->

```
    Internal/Commands/RedisSubscription.cs(15,18): warning CS0219: The variable `count' is assigned but its value is never used
    Internal/IO/RedisReader.cs(56,17): warning CS0219: The variable `bytes_remaining' is assigned but its value is never used
```

Errors:

/home/harm/CoiniumServ/build/CoiniumServ.sln (default targets) ->
(Build target) ->
/home/harm/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/home/harm/CoiniumServ/build/.nuget/NuGet.targets (RestorePackages target) ->

```
    /home/harm/CoiniumServ/build/.nuget/NuGet.targets: error : Command 'mono --runtime=v4.0.30319 /home/harm/CoiniumServ/build/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/home/harm/CoiniumServ/build/"' exited with code: 1.

     2 Warning(s)
     1 Error(s)
```

Time Elapsed 00:00:03.9628960
xUnit.net console test runner (64-bit .NET 4.0.30319.1)
Copyright (C) 2013 Outercurve Foundation.

error: file not found: src/Tests/bin/Release/CoiniumServ.Tests.dll
##

**Comment by computeronix** [comment]
resolved

**Comment by foxer666** [comment]
Not resolved.
`
Build FAILED.
Errors:

/root/CoiniumServ/build/CoiniumServ.sln (default targets) ->
(Build target) ->
/root/CoiniumServ/src/CoiniumServ/CoiniumServ.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        Algorithms/Implementations/X13.cs(51,17): error CS0120: An object reference is required for the non-static field, method, or property 'List<IHash>.Add(IHash)'

         0 Warning(s)
         1 Error(s)

Time Elapsed 00:01:14.6104760
xUnit.net console test runner (32-bit .NET 4.0.30319.42000)
Copyright (C) 2013 Outercurve Foundation.

error: file not found: src/Tests/bin/Release/CoiniumServ.Tests.dll
`
