### ISSUE TITLE
RedisProvider and Pool initilization failed; Nancy.TinyIoc.

### ISSUE THREAD

**Issue by danycoman** [bonesoul/CoiniumServ#868]
17:35:36 [Error] [RedisProvider] [Kittehcoin] Redis storage initialization failed: 127.0.0.1:6379 - This method is not implemented by this class.
17:35:37 [Error] [Pool] [Kittehcoin] Pool initilization failed; Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Persistance.Layers.Hybrid.IMigrationManager ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Persistance.Layers.Hybrid.MigrationManager ---> System.NullReferenceException: Object reference not set to an instance of an object
  at FluentMigrator.Runner.Processors.DbFactoryBase.CreateDataAdapter (System.Data.IDbCommand command) [0x0000b] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.Read (System.String template, System.Object[] args) [0x0003c] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.ReadTableData (System.String schemaName, System.String tableName) [0x0001a] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.VersionLoader.LoadVersionInfo () [0x000d0] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.VersionLoader..ctor (FluentMigrator.Runner.IMigrationRunner runner, FluentMigrator.Infrastructure.IAssemblyCollection assemblies, FluentMigrator.IMigrationConventions conventions) [0x00077] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.MigrationRunner..ctor (FluentMigrator.Infrastructure.IAssemblyCollection assemblies, FluentMigrator.Runner.Initialization.IRunnerContext runnerContext, FluentMigrator.IMigrationProcessor processor) [0x00175] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.MigrationRunner..ctor (System.Reflection.Assembly assembly, FluentMigrator.Runner.Initialization.IRunnerContext runnerContext, FluentMigrator.IMigrationProcessor processor) [0x00007] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at CoiniumServ.Persistance.Layers.Hybrid.MigrationManager.Check () [0x0004a] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at CoiniumServ.Persistance.Layers.Hybrid.MigrationManager..ctor (CoiniumServ.Persistance.Providers.MySql.IMySqlProvider provider, CoiniumServ.Pools.IPoolConfig poolConfig) [0x0002e] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object[])
  at Nancy.TinyIoc.TinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x000f7] in <bb3027f50b35411088f45475912cc2ff>:0
   --- End of inner exception stack trace ---
  at Nancy.TinyIoc.TinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x0010d] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer+MultiInstanceFactory.GetObject (System.Type requestedType, Nancy.TinyIoc.TinyIoCContainer container, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x0000e] in <bb3027f50b35411088f45475912cc2ff>:0
   --- End of inner exception stack trace ---
  at Nancy.TinyIoc.TinyIoCContainer+MultiInstanceFactory.GetObject (System.Type requestedType, Nancy.TinyIoc.TinyIoCContainer container, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x00026] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal (Nancy.TinyIoc.TinyIoCContainer+TypeRegistration registration, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x00027] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer.Resolve (System.Type resolveType, Nancy.TinyIoc.NamedParameterOverloads parameters) [0x0000d] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer.Resolve[ResolveType] (Nancy.TinyIoc.NamedParameterOverloads parameters) [0x00000] in <bb3027f50b35411088f45475912cc2ff>:0
  at CoiniumServ.Container.ObjectFactory.GetMigrationManager (CoiniumServ.Persistance.Providers.MySql.IMySqlProvider provider, CoiniumServ.Pools.IPoolConfig poolConfig) [0x00029] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at CoiniumServ.Pools.Pool.InitStorage () [0x00079] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at CoiniumServ.Pools.Pool.Initialize () [0x00048] in <d6afe335750e44a587b42c52bc37a1e4>:0

**Comment by gecox22** [comment]
Looks like you are not connecting you Redis or MySQL did you setup the username and password for Mysql and open ports for redis and mysql?

**Comment by danycoman** [comment]
11:03:43 [Information] [ConfigManager] [global] CoiniumServ Atilla 0.2.6.1 warming-up..
11:03:43 [Information] [PlatformManager] [global] Running over Mono 5.4.1.6 (tarball Wed Nov  8 20:37:08 UTC 2017), framework: 4.5 (v4.0.30319.42000).
11:03:50 [Information] [ConfigManager] [global] Discovered a total of 1 enabled pool configurations: [Octocoin]
11:03:50 [Information] [MySqlProvider] [Octocoin] Mysql storage initialized: 127.0.0.1:3306, database: crypto.
11:03:50 [Information] [RedisProvider] [Octocoin] Redis storage initialized: 127.0.0.1:4379, v3.0.6.
11:03:51 [Error] [Pool] [Octocoin] Pool initilization failed; Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Persistance.Layers.Hybrid.IMigrationManager ---> Nancy.TinyIoc.TinyIoCResolutionException: Unable to resolve type: CoiniumServ.Persistance.Layers.Hybrid.MigrationManager ---> System.NullReferenceException: Object reference not set to an instance of an object
  at FluentMigrator.Runner.Processors.DbFactoryBase.CreateDataAdapter (System.Data.IDbCommand command) [0x0000b] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.Read (System.String template, System.Object[] args) [0x0003c] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.Processors.MySql.MySqlProcessor.ReadTableData (System.String schemaName, System.String tableName) [0x0001a] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.VersionLoader.LoadVersionInfo () [0x000d0] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.VersionLoader..ctor (FluentMigrator.Runner.IMigrationRunner runner, FluentMigrator.Infrastructure.IAssemblyCollection assemblies, FluentMigrator.IMigrationConventions conventions) [0x00077] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.MigrationRunner..ctor (FluentMigrator.Infrastructure.IAssemblyCollection assemblies, FluentMigrator.Runner.Initialization.IRunnerContext runnerContext, FluentMigrator.IMigrationProcessor processor) [0x00175] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at FluentMigrator.Runner.MigrationRunner..ctor (System.Reflection.Assembly assembly, FluentMigrator.Runner.Initialization.IRunnerContext runnerContext, FluentMigrator.IMigrationProcessor processor) [0x00007] in <137fb96feee44f379d6a8fba4e172d1c>:0
  at CoiniumServ.Persistance.Layers.Hybrid.MigrationManager.Check () [0x0004a] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at CoiniumServ.Persistance.Layers.Hybrid.MigrationManager..ctor (CoiniumServ.Persistance.Providers.MySql.IMySqlProvider provider, CoiniumServ.Pools.IPoolConfig poolConfig) [0x0002e] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object[])
  at Nancy.TinyIoc.TinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x000f7] in <bb3027f50b35411088f45475912cc2ff>:0
   --- End of inner exception stack trace ---
  at Nancy.TinyIoc.TinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x0010d] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer+MultiInstanceFactory.GetObject (System.Type requestedType, Nancy.TinyIoc.TinyIoCContainer container, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x0000e] in <bb3027f50b35411088f45475912cc2ff>:0
   --- End of inner exception stack trace ---
  at Nancy.TinyIoc.TinyIoCContainer+MultiInstanceFactory.GetObject (System.Type requestedType, Nancy.TinyIoc.TinyIoCContainer container, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x00026] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer.ResolveInternal (Nancy.TinyIoc.TinyIoCContainer+TypeRegistration registration, Nancy.TinyIoc.NamedParameterOverloads parameters, Nancy.TinyIoc.ResolveOptions options) [0x00027] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer.Resolve (System.Type resolveType, Nancy.TinyIoc.NamedParameterOverloads parameters) [0x0000d] in <bb3027f50b35411088f45475912cc2ff>:0
  at Nancy.TinyIoc.TinyIoCContainer.Resolve[ResolveType] (Nancy.TinyIoc.NamedParameterOverloads parameters) [0x00000] in <bb3027f50b35411088f45475912cc2ff>:0
  at CoiniumServ.Container.ObjectFactory.GetMigrationManager (CoiniumServ.Persistance.Providers.MySql.IMySqlProvider provider, CoiniumServ.Pools.IPoolConfig poolConfig) [0x00029] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at CoiniumServ.Pools.Pool.InitStorage () [0x00079] in <d6afe335750e44a587b42c52bc37a1e4>:0
  at CoiniumServ.Pools.Pool.Initialize () [0x00048] in <d6afe335750e44a587b42c52bc37a1e4>:0
11:03:52 [Information] [WebServer] [global] Web-server listening on: http://localhost/

**Comment by danycoman** [comment]
![image](https://user-images.githubusercontent.com/30026820/32901498-9b6ed640-caf8-11e7-90a9-03ed0e9bbd58.png)

**Comment by danycoman** [comment]
need a special setup at sql? We just created a database with the name crypto, nothing special.

**Comment by gecox22** [comment]
Are you building the coiniumserv develop or the coiumserv master? I just went through the same issues two days ago and found I was trying to build the develop one. Once I downloaded the master it was fine. As for the mysql database base just need a name coinium added the tables and info. Just remove to update the tables when your done for blocks, Payments.

**Comment by danycoman** [comment]
I do not know anymore :( What is the updated source better? Can you leave me a link? Thank you for your support!

**Comment by danycoman** [comment]
23 Warning(s)
         600 Error(s)

I try to build new ,edit source but ////

**Comment by gecox22** [comment]
Click on code from here then click on branches. There are two branches Development and Master click on master and then clone or download that branch once the page loads.

**Comment by danycoman** [comment]
Unfortunately, we did not succeed, we only had a good version of it but had problems with statistics.

Abandoning, I'm sorry I liked it a lot.

**Comment by gecox22** [comment]
what was wrong with the statistics?

**Comment by danycoman** [comment]
In short,

A few months ago, I downloaded a good version here that did not run the statistics, and I resolved with cred, I changed that dll /

The problem was to share, we tested the scrypt, and there were no miners with more power than 1M gen, minerrenal, nicehash.

Now because of the many miners who ask for statistics I have to install something ..

I've reinvented again with this platform but get the above error. I can not make it go.


At the moment, I'm using a nomp platform that I have not found anything to adjust for payout or estimated reward,

this is my pool .altcoin.mine-pool.ro works well only on pre-set algo.

If there is someone to provide a good source, and to spit out the dependencies that best lujcrest.


Thanks for the reply

**Comment by Netzarim** [comment]
I've got CoiniumServ working for X11 and Skein coins... Except for the Redis issue.  I still cannot seem to get it to connect, however I did get unomp to connect without issue.  This is the only thing holding me back from taking this server live as the stats are not there.

**Comment by rvrsh3ll** [comment]
Same issue with stats. Any resolution?
